### ISSUE TITLE
OSError: No Default Input Device Available

### ISSUE THREAD

**Issue by abinzzz** [olaDEN/Ai-Voice-Chatter-python-streamlit#1]
(y10) root@b11a13895df1:/cyb/chat/SoulChat/Ai-Voice-Chatter-python-streamlit# pip install PyAudio
Requirement already satisfied: PyAudio in /root/anaconda3/envs/y10/lib/python3.9/site-packages (0.2.14)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(y10) root@b11a13895df1:/cyb/chat/SoulChat/Ai-Voice-Chatter-python-streamlit# streamlit run Chatter.py --server.port 8030

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8030
  Network URL: http://172.17.0.4:8030
  External URL: http://159.226.182.212:8030

pygame 2.5.2 (SDL 2.28.2, Python 3.9.19)
Hello from the pygame community. https://www.pygame.org/contribute.html
/root/anaconda3/envs/y10/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/root/anaconda3/envs/y10/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
2024-06-17 23:53:17.230 `st.cache` is deprecated. Please use one of Streamlit's new caching commands,
`st.cache_data` or `st.cache_resource`.

More information [in our docs](https://docs.streamlit.io/library/advanced-features/caching).
2024-06-17 23:53:17.322 Uncaught app exception
Traceback (most recent call last):
  File "/root/anaconda3/envs/y10/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/cyb/chat/SoulChat/Ai-Voice-Chatter-python-streamlit/Chatter.py", line 27, in <module>
    mic = sr.Microphone()
  File "/root/anaconda3/envs/y10/lib/python3.9/site-packages/speech_recognition/__init__.py", line 87, in __init__
    device_info = audio.get_device_info_by_index(device_index) if device_index is not None else audio.get_default_input_device_info()
  File "/root/anaconda3/envs/y10/lib/python3.9/site-packages/pyaudio/__init__.py", line 812, in get_default_input_device_info
    device_index = pa.get_default_input_device()
OSError: No Default Input Device Available
2024-06-17 23:53:27.655 `st.cache` is deprecated. Please use one of Streamlit's new caching commands,
`st.cache_data` or `st.cache_resource`.

More information [in our docs](https://docs.streamlit.io/library/advanced-features/caching).
2024-06-17 23:53:27.656 Uncaught app exception
Traceback (most recent call last):
  File "/root/anaconda3/envs/y10/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/cyb/chat/SoulChat/Ai-Voice-Chatter-python-streamlit/Chatter.py", line 27, in <module>
    mic = sr.Microphone()
  File "/root/anaconda3/envs/y10/lib/python3.9/site-packages/speech_recognition/__init__.py", line 87, in __init__
    device_info = audio.get_device_info_by_index(device_index) if device_index is not None else audio.get_default_input_device_info()
  File "/root/anaconda3/envs/y10/lib/python3.9/site-packages/pyaudio/__init__.py", line 812, in get_default_input_device_info
    device_index = pa.get_default_input_device()
OSError: No Default Input Device Available

**Comment by abinzzz** [comment]
help me！
